### ISSUE TITLE
cant find send_file() method 

### ISSUE THREAD

**Issue by theappol78qwe** [czifro-development/JSocket#12]
i am using Jsocket for transfering files but i cant find send_file() method is it removed or its replaced ??

**Comment by czifro** [comment]
First off, thank you for using my library. File transferring is a feature that was removed from Jsocket. The reason is, since Jsocket is a library that simply wraps around a java.net.Socket object, it does not implement a protocol. To incorporate file transferring would require implementing a protocol. If the library were to implement a protocol, it may interfere with a protocol implemented by the user. Another reason for removing it was the fact that it was still quite buggy. I wanted to proceed with a library that had a minimal amount of bugs. I will not rule out including this as a feature in the future, or I might make a separate library for transferring files. Apologies if this is an inconvenience.

My I ask which version of Jsocket you are using? It seems you might be using a slightly older version, especially if you are looking for the file transfer feature. I am currently working on vNext 0.5.0. I've just released the first and second beta. It is a complete rewrite of the library, so swapping out an older version with this version may break things since it is not backwards compatible. However, connecting via TCP to an older version should work just fine. I'm working on updating documentation for it, but feel free to check it out.

**Comment by theappol78qwe** [comment]
Thank you for your response
i am using 0.3.1 I think
i am using the last one on github
i am hoping u create one for FTP
thank you

**Comment by czifro** [comment]
The latest one on github is v0.4.2. In the wikis I mention that I removed FTP from the library due to its inconsistency in reliability. If this is a feature that you immediately need, it is in [v0.4.1](https://www.dropbox.com/s/4wpj0x2jawuckq1/jsocket-0.4.1--unstable.jar?dl=0), which was considered unstable because of the FTP feature. 

FTP was a feature that I regrettably had to pull out; however, I have reached a point where I am content with the available features. Should the use of this library increase and requests for new features be made, I'll add more features. My goal though is to just optimize and simplify the library. 

I have created a separate repo for FTP: [instant-transmission](https://github.com/czifro-tech/instant-transmission) . I will probably start working on it once I finish v0.5.0 of this library, since I'll probably use this library as a dependency. I would watch that repo to get updates on the progress of that library.

Thanks for supporting this library and my work.
